USE ROLE SYSADMIN;
USE FINANCEDW;
USE SCHEMA "FINANCEDW"."NDS";


-- CREATE STAGE
CREATE STAGE IF NOT EXISTS "FINANCEDW"."NDS".PYTHON_API_STAGE;
-- CREATE FILE_CSV FORMAT
CREATE FILE FORMAT IF NOT EXISTS "FINANCEDW"."NDS".CSV_FILE TYPE = 'CSV' COMPRESSION = 'AUTO' 
FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 0 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' 
TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' 
DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');

CREATE FILE FORMAT IF NOT EXISTS "FINANCEDW"."FinanceDatawarehouse".CSV_FILE TYPE = 'CSV' COMPRESSION = 'AUTO' 
FIELD_DELIMITER = ',' RECORD_DELIMITER = '\n' SKIP_HEADER = 0 FIELD_OPTIONALLY_ENCLOSED_BY = 'NONE' 
TRIM_SPACE = FALSE ERROR_ON_COLUMN_COUNT_MISMATCH = TRUE ESCAPE = 'NONE' ESCAPE_UNENCLOSED_FIELD = '\134' 
DATE_FORMAT = 'AUTO' TIMESTAMP_FORMAT = 'AUTO' NULL_IF = ('\\N');


-- desc user NhatLQ3;
USE ROLE ACCOUNTADMIN;
ALTER USER NhatLQ3 SET rsa_public_key = 
'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAs3XuSpWounMfBdA0E1Ub
zlJi0MIZjbU/QPdWlIaPDjPLE+y6DJ561hQjBIzWKx0uySEOWvezCSE3glO6ZKRb
3bY5XXpcBaifPuTsBs1NgCH3nAbeoxxjwrkzGehDjC5JbblJ/9yVQkY42dfBqwgN
s8DA4MwigAOKuX6v0XR2ank0X63MEiy4SIu0itHHNb/Rv2T0xWj2woDLrgjmMyrP
9Nc7g+UbcGWPQ8eQjDylrQBNT9HJXd8R1rzlzE2A5hO8wFN5vRqt30x0Qvv4gcBb
X1HSuIVxA/w3Pv54FKbEKWOoj3VVuO8tSRkSfad7aWaFFNyGwE9XvYL1PUDMtghF
BQIDAQAB';


-- CREATE FINANCE_STREAM TABLE TO MERGE WITH FACTFINACE (IN ORDER TO AVOID DUPLICATING DATA CAUSED BY SNOWPIPE)
USE ROLE SYSADMIN;
CREATE TABLE IF NOT EXISTS "FINANCEDW"."NDS".FINANCE_STREAM (
	transactionID int not null,
    CustomerKey  int not null,
	startDateKey int not null,
	endDateKey int not null,
	-- measure
 	loan int not null,
	creditscore int not null,
	-- constraints
 	CONSTRAINT PK_FactFinance PRIMARY KEY (transactionID)
)
COMMENT = 'STREAM DATA TO THIS TABLE AND MERGE TO AVOID DUPLICATE DATA';


-- CREATE PIPE
USE ROLE SYSADMIN;
CREATE PIPE IF NOT EXISTS "FINANCEDW"."NDS".FINANCE_PIPE AS COPY INTO "FINANCEDW"."NDS"."FINANCE_STREAM" 
FROM @"FINANCEDW"."NDS"."PYTHON_API_STAGE" FILE_FORMAT = (FORMAT_NAME = "FINANCEDW"."NDS"."CSV_FILE");










